# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:boot-2.7.1
        # https://discuss.circleci.com/t/builds-getting-killed-with-vague-message-received-signal-killed/10214/9
        command: "/bin/bash"

    working_directory: ~/repo

    environment:
      BOOT_JVM_OPTIONS: -Xmx2048m # Customize the JVM maximum heap limit
      CLJDOC_PROFILE: test

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
          - v1-dependencies- # fallback if not cache found

      - run:
          name: Install CLI tools
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.9.0.381.sh
            chmod +x linux-install-1.9.0.381.sh
            sudo ./linux-install-1.9.0.381.sh

      - run: clojure -Spath
      - run: mkdir test-data

      - run: ./script/cljdoc ingest --project bidi --version 2.1.3
      - run: ./script/analyze.sh bidi 2.1.3 ~/.m2/repository/bidi/bidi/2.1.3/bidi-2.1.3.jar ~/.m2/repository/bidi/bidi/2.1.3/bidi-2.1.3.pom

      - run: clojure -A:test
      - store_test_results:
          path: target/

      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot
          key: v1-dependencies-{{ checksum "deps.edn" }}
