# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:boot-2.7.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.boot" }}
          - v1-dependencies- # fallback if not cache found

      - run: boot show -d

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.boot" }}

      - run: boot repl -e "(do (println :test) (System/exit 0))"