# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:boot-2.7.1
        # https://discuss.circleci.com/t/builds-getting-killed-with-vague-message-received-signal-killed/10214/9
        cmd: ["/bin/bash"]

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.boot" }}
          - v1-dependencies- # fallback if not cache found

      - run: boot show -d
      - run: boot -B -d codox

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.boot" }}

      - run: boot build-docs --project bidi --version 2.1.3